# Generated by Django 5.1 on 2024-09-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_files_user_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='comment',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='files',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
