# Generated by Django 5.1 on 2024-09-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_files_comment_files_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='image',
            field=models.ImageField(default='', upload_to='storage_files'),
        ),
    ]
