# Generated by Django 5.1 on 2024-09-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_files_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='path_to_file',
        ),
    ]
