# Generated by Django 5.1 on 2024-09-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_remove_users_path_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
