# Generated by Django 5.1 on 2024-09-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='image',
            field=models.FileField(default='', upload_to='storage_files'),
        ),
    ]
