# Generated by Django 5.1 on 2024-09-24 21:05

import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_files_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='last_download',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='image',
            field=models.FileField(default='', upload_to=storage.models.user_path),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default='USER', max_length=100),
        ),
    ]
