# Generated by Django 5.1 on 2024-09-27 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_files_last_download_alter_files_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='image',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='files',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='files',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='files',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storage.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default='USER', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
