# Generated by Django 5.1 on 2024-09-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_alter_files_comment_alter_files_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
